### ISSUE TITLE
这个 Mac 版构建的 luajit 好像有点问题

### ISSUE THREAD

**Issue by dyphire** [eko5624/mpv-macos-intel#9]
有些 lua 脚本在这个 mac 版本中不受支持，错误信息
<img width="1243" alt="image" src="https://github.com/eko5624/mpv-macos-intel/assets/61936050/4b478ddd-f72f-432e-8ba6-1ebaabc7b022">
脚本： [recentmenu.lua](https://github.com/natural-harmonia-gropius/recent-menu/blob/master/recentmenu.lua)

**Comment by eko5624** [comment]
这个我也不知道啥原因。尝试换 https://github.com/LuaJIT/LuaJIT.git 编译也是同样的报错信息。

**Comment by dyphire** [comment]
> 这个我也不知道啥原因。尝试换 https://github.com/LuaJIT/LuaJIT.git 编译也是同样的报错信息。

在 windows 上是正常的，感觉是 mac 构建脚本产生的特异点

**Comment by eko5624** [comment]
测试了下mpv仓库自动编译的版本，也是一样的问题。
https://github.com/mpv-player/mpv/actions/runs/8677438849/artifacts/1411645933

**Comment by dyphire** [comment]
由 https://github.com/natural-harmonia-gropius/recent-menu/commit/70a2083c96c69089afd9b99f36b6b7edfb173108 修复脚本解释器错误
